### PR TITLE
Add `entries_for_feed` method

### PR DESCRIPTION
**Pull request by twe4ked**
Also tweaks/updates a bunch of other stuff. Take what you will :smile:

### CODE REVIEW

**Comment by cp** [comment]
@twe4ked hey! somehow I was never notified about this, and just saw it. :cry: if you could rebase this into one commit, I would love to merge it!

**Comment by twe4ked** [comment]
The commits aren't very related though. I don't feel it belongs in a single commit. I'm not using the API anymore. Feel free to squash/merge if you want to. Happy to just close this though.

**Comment by cp** [comment]
@twe4ked Good point. I went ahead and merged it. Thanks! :smile:

**Comment by twe4ked** [comment]
No worries, cheers :)

**Pull request merged**
